# https://starship.rs/config

"$schema" = "https://starship.rs/config-schema.json"

add_newline = false

format = """$cmd_duration
$username\
$hostname\
$localip\
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$sudo\
$line_break\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""

[aws]
disabled = true
symbol = " "

[cmd_duration]
format = "took [$duration]($style)\n"

[directory]
style = "bold blue"
read_only = ""
read_only_style = "dimmed red"
truncation_length = 8
truncation_symbol = "… "
truncate_to_repo = false
before_repo_root_style = "dimmed bold blue"
repo_root_style = "bold blue"

[dotnet]
format = "via [$symbol($version )( $tfm )]($style)"
style = "blue"
symbol = " "
heuristic = true

[git_branch]
symbol = " "

[git_status]
style = "bold purple"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
windows_starship = "/c/users/user/scoop/apps/starship/current/starship.exe"

[helm]
symbol = "⎈ "

[java]
style = "dimmed purple"

[kubernetes]
symbol = "⎈ "

[line_break]
disabled = false

[nodejs]
style = "dimmed green"

[package]
style = "dimmed white"

[rust]
style = "dimmed red"

[shell]
disabled = false
format = "[$indicator]($style)"
style = "bold green"
bash_indicator = "bash"
cmd_indicator = "cmd"
powershell_indicator = "ps"
pwsh_indicator = "pwsh"
zsh_indicator = "zsh"

[shlvl]
disabled = false
format = "[$symbol]($style) "
repeat = true
repeat_offset = 1
symbol = "❯"
