//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file is automatically generated by RisohEditor 5.7.8.
// app_three.rc

#define IDR_MAINMENU                        102

#define ID_FILE_EXIT                        40001
#define ID_FILE_OPEN                        40002
#define ID_FILE_SAVEAS                      40003
#define ID_FILE_NEW                         40004
#define IDC_STATIC -1
#define IDD_MAIN                        101
#define IDC_TEXT                        1000
#define IDC_NUMBER                      1001
#define IDC_LIST                        1002
#define IDC_ADD                         1003
#define IDC_CLEAR                       1004
#define IDC_REMOVE                      1005
#define IDC_SHOWCOUNT                   1006


#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    103
        #define _APS_NEXT_COMMAND_VALUE     40005
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
