# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.16

# compile C with C:/stuff/libs/C/mingw64/bin/gcc.exe
C_FLAGS = -g  

C_DEFINES = 

C_INCLUDES = @CMakeFiles/ctl_one.c.dir/includes_C.rsp

