# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.16

# compile C with C:/stuff/libs/C/mingw64/bin/gcc.exe
# compile RC with C:/stuff/libs/C/mingw64/bin/windres.exe
C_FLAGS = -g  

C_DEFINES = 

C_INCLUDES = @CMakeFiles/app_three.dir/includes_C.rsp

RC_FLAGS =  

RC_DEFINES = 

RC_INCLUDES = -ID:\source\app_three\. 

