# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.16

CMakeFiles/app_three.dir/app_three.c.obj: ../app_three.c
CMakeFiles/app_three.dir/app_three.c.obj: ../resource.h

CMakeFiles/app_three.dir/app_three.rc.obj: ../app_three.rc
CMakeFiles/app_three.dir/app_three.rc.obj: ../resource.h

CMakeFiles/app_three.dir/ctl_one.rc.obj: ../ctl_one.rc
CMakeFiles/app_three.dir/ctl_one.rc.obj: ../resource.h

