# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.16

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "D:\Tools\Clion\CLion 2020.1.2\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "D:\Tools\Clion\CLion 2020.1.2\bin\cmake\win\bin\cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = D:\source\app_three

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = D:\source\app_three\cmake-build-debug

# Include any dependencies generated for this target.
include CMakeFiles/app_three.dir/depend.make

# Include the progress variables for this target.
include CMakeFiles/app_three.dir/progress.make

# Include the compile flags for this target's objects.
include CMakeFiles/app_three.dir/flags.make

CMakeFiles/app_three.dir/app_three.c.obj: CMakeFiles/app_three.dir/flags.make
CMakeFiles/app_three.dir/app_three.c.obj: CMakeFiles/app_three.dir/includes_C.rsp
CMakeFiles/app_three.dir/app_three.c.obj: ../app_three.c
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=D:\source\app_three\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Building C object CMakeFiles/app_three.dir/app_three.c.obj"
	C:\stuff\libs\C\mingw64\bin\gcc.exe $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -o CMakeFiles\app_three.dir\app_three.c.obj   -c D:\source\app_three\app_three.c

CMakeFiles/app_three.dir/app_three.c.i: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Preprocessing C source to CMakeFiles/app_three.dir/app_three.c.i"
	C:\stuff\libs\C\mingw64\bin\gcc.exe $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -E D:\source\app_three\app_three.c > CMakeFiles\app_three.dir\app_three.c.i

CMakeFiles/app_three.dir/app_three.c.s: cmake_force
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green "Compiling C source to assembly CMakeFiles/app_three.dir/app_three.c.s"
	C:\stuff\libs\C\mingw64\bin\gcc.exe $(C_DEFINES) $(C_INCLUDES) $(C_FLAGS) -S D:\source\app_three\app_three.c -o CMakeFiles\app_three.dir\app_three.c.s

CMakeFiles/app_three.dir/app_three.rc.obj: CMakeFiles/app_three.dir/flags.make
CMakeFiles/app_three.dir/app_three.rc.obj: ../app_three.rc
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=D:\source\app_three\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_2) "Building RC object CMakeFiles/app_three.dir/app_three.rc.obj"
	C:\stuff\libs\C\mingw64\bin\windres.exe -O coff $(RC_DEFINES) $(RC_INCLUDES) $(RC_FLAGS) D:\source\app_three\app_three.rc CMakeFiles\app_three.dir\app_three.rc.obj

CMakeFiles/app_three.dir/ctl_one.rc.obj: CMakeFiles/app_three.dir/flags.make
CMakeFiles/app_three.dir/ctl_one.rc.obj: ../ctl_one.rc
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --progress-dir=D:\source\app_three\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_3) "Building RC object CMakeFiles/app_three.dir/ctl_one.rc.obj"
	C:\stuff\libs\C\mingw64\bin\windres.exe -O coff $(RC_DEFINES) $(RC_INCLUDES) $(RC_FLAGS) D:\source\app_three\ctl_one.rc CMakeFiles\app_three.dir\ctl_one.rc.obj

# Object files for target app_three
app_three_OBJECTS = \
"CMakeFiles/app_three.dir/app_three.c.obj" \
"CMakeFiles/app_three.dir/app_three.rc.obj" \
"CMakeFiles/app_three.dir/ctl_one.rc.obj"

# External object files for target app_three
app_three_EXTERNAL_OBJECTS =

app_three.exe: CMakeFiles/app_three.dir/app_three.c.obj
app_three.exe: CMakeFiles/app_three.dir/app_three.rc.obj
app_three.exe: CMakeFiles/app_three.dir/ctl_one.rc.obj
app_three.exe: CMakeFiles/app_three.dir/build.make
app_three.exe: CMakeFiles/app_three.dir/linklibs.rsp
app_three.exe: CMakeFiles/app_three.dir/objects1.rsp
app_three.exe: CMakeFiles/app_three.dir/link.txt
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --green --bold --progress-dir=D:\source\app_three\cmake-build-debug\CMakeFiles --progress-num=$(CMAKE_PROGRESS_4) "Linking C executable app_three.exe"
	$(CMAKE_COMMAND) -E cmake_link_script CMakeFiles\app_three.dir\link.txt --verbose=$(VERBOSE)

# Rule to build all files generated by this target.
CMakeFiles/app_three.dir/build: app_three.exe

.PHONY : CMakeFiles/app_three.dir/build

CMakeFiles/app_three.dir/clean:
	$(CMAKE_COMMAND) -P CMakeFiles\app_three.dir\cmake_clean.cmake
.PHONY : CMakeFiles/app_three.dir/clean

CMakeFiles/app_three.dir/depend:
	$(CMAKE_COMMAND) -E cmake_depends "MinGW Makefiles" D:\source\app_three D:\source\app_three D:\source\app_three\cmake-build-debug D:\source\app_three\cmake-build-debug D:\source\app_three\cmake-build-debug\CMakeFiles\app_three.dir\DependInfo.cmake --color=$(COLOR)
.PHONY : CMakeFiles/app_three.dir/depend

