git update-git-for-windows # update to newest version on windows
git stash # save local modifications
git reset --hard 26b6d18 # hash before commit, destroys any local modifications!
git push --force (or git push -f) # all commits after reset will be deleted from history
git stash pop # reapply 

git rm #remove file from repository
git svn clone ... ... # get the latest source from SVN ...
git checkout master # ... 
git svn rebase # ...
git diff master # check differencies between modified and remote  
git reset --hard HEAD^ # reset to previous
git revert HEAD # revert to previous, new commit 
git revert --no-commit 0766c053..HEAD # revert to commit ...
git commit # and commit as HEAD ...
git grep -z --full-name -l '.' | xargs -0 sed -i -e 's/old-text/new-text/ig' # find and replace text in all files of a repository
git branch -m old_branch new_branch # Rename branch locally  ...  
git push origin :old_branch                 # Delete the old branch  ...  
git push --set-upstream origin new_branch   # Push the new branch, set local branch to track the new remote ...
gitk # gui for git  

# If you worked in wrong branch
git stash
git checkout main
git stash apply