bundle update github-pages #update to newest gems for github-pages inside repo ...
gem update github-pages # dito ...
bundle info --path minima #show where gem is located in project
https://api.github.com/emojis # markdown emojis :om:
git clone git@github.com:4997128.git #clone gist over ssh, add files like images, commit, push