name: Sync GitHub Gists
on:
  workflow_dispatch:
env:
  API_TOKEN: ${{secrets.API_TOKEN}}
  GITHUB_TOKEN: ${{github.token}}
  TAG: ${{github.ref_name}}
  TDATE: '2024OCT23'
  permission: write
jobs:
  sync:
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: bash
        working-directory: ${{github.workspace}}
    steps:
    - name: 'Checkout Repo'
      uses: actions/checkout@v4
      with:
        cwd: ${{github.workspace}}
    
    - name: 'Install JQ'
      # You may pin to the exact commit or the version.
      # uses: dcarbone/install-jq-action@8867ddb4788346d7c22b72ea2e2ffe4d514c7bcb
      uses: dcarbone/install-jq-action@v2.1.0          
    
    - name: 'Gist to GitHub Import'
      id: strings
      shell: bash
      run: |
        data="$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $API_TOKEN" -H "X-GitHub-Api-Version: 2022-11-28" 'https://api.github.com/users/pa-0/gists')"
        
        IFS=$' ' # parsing the string
        urls="$(echo "$data" | jq -r .[].files | jq -r .[].raw_url)"
        descriptions="$(echo "$data" | jq -r .[].description)"
        nb_comments="$(echo "$data" | jq -r .[].comments)"
        comments_urls="$(echo "$data" | jq -r .[].comments_url)"
        
        IFS=$'\n' # parsing the array
        urls=($urls)
        descriptions=($descriptions)
        nb_comments=($nb_comments)
        comments_urls=($comments_urls)
        
        index=0
        
        for url in "${urls[@]}"
        do
        	gist="$(curl -s $url)"
        
        	filename="$(echo $url | cut -f8 -d /)" # parse url to get filename
        
        	subfolder="$filename"
        	mkdir "$subfolder" 2>/dev/null # create directory for each gist
        
        	readme="$subfolder/README.md"
        
        	echo "${descriptions[index]}" > "$readme" # write gist description
        	echo -e "---------------\n" >> "$readme"
        	echo -n "### " >> "$readme" # url will be h3 in markdown
        	echo "$data" | jq -r .["$index"].html_url >> "$readme" # write url to gist.github.com
        	echo "$gist" > "$subfolder"/"$filename" # write code
        	if [ "${nb_comments[index]}" -ne 0 ]
        	then
        	    comment="$(curl -s ${comments_urls[index]})"
        	    comment_body="$(echo $comment | jq -r .[].body)"
        	    echo -e "---------------\n\n" >> "$readme"
        	    echo "$comment_body" >> "$readme" # write comments in README if there are any
        	fi
        
        	echo -e "\e[033m" "$filename" : "\e[32m" DONE "\e[0m\n"
        	let "index+=1"
        done
        
    - name: 'Add & Commit'
      uses: EndBug/add-and-commit@v9.1.4
      with:
        # The directory where your repository is located. You should use actions/checkout first to set it up
        cwd: ${{github.workspace}}
        message: 'Imported via GitHub Action'
        new_branch: "import_${{env.TDATE}}"
